[project]
name = "crossreads_petrography"
version = "0.2.0"
description = "A package for petrography analysis in the Crossreads project"
authors = [{ name = "Ryan Heuser", email = "ryan.heuser@kcl.ac.uk" }]
requires-python = ">=3.7"
readme = "README.md"
dependencies = [
    "pandas",
    "gspread",
    "google-auth",
    "loguru",
    "shapely",
    "plotly",
    "scipy",
    "openpyxl",
    "nbformat>=4.2.0",
    "ipython",
    "kaleido",
    "scikit-learn",
    "plotnine",
    "pyyaml",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[build-system]
requires = ["setuptools>=62.6", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = false

[tool.setuptools]
packages = ["crossreads_petrography"]
include-package-data = true

[tool.setuptools.package-data]
"crossreads_petrography" = ["../data/**/*"]

[dependency-groups]
dev = [
    "ipykernel>=6.16.2",
    "jupyter>=1.1.1",
    "pip>=24.0",
    "pytest>=7.4.4",
]
