[build-system]
requires = ["setuptools>=62.6", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crossreads_petrography"
version = "0.1.0"
description = "A package for petrography analysis in the Crossreads project"
authors = [{name = "Ryan Heuser", email = "ryan.heuser@kcl.ac.uk"}]
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools]
packages = ["crossreads_petrography"]
include-package-data = true

[tool.setuptools.package-data]
"crossreads_petrography" = ["../data/**/*"]